name: Publish to Release

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build
        run: make workflows
      - name: Release
        uses: actions/checkout@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: bash-learner
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
