name: Publish to Release

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: make workflows
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: bash-learner
        asset_name: bash-learnermacosx
        tag: ${{ github.ref }}
        overwrite: true
        body: "This is the binary for macosx"
